[package]
name = "gateway-cypht"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gateway-auth = { path = "../gateway-auth" }
gateway-core = { path = "../gateway-core" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
